export const colors = {
	COLOR_PRIMARY: "#f96163",
	COLOR_LIGHT: "#fff",
	COLOR_DARK: "#000",
	COLOR_DARK_ALT: "#262626",
};

export const categories = [
	{
		id: "01",
		category: "Breakfast",
	},
	{
		id: "02",
		category: "Lunch",
	},
	{
		id: "03",
		category: "Dinner",
	},
];

export const recipeList = [
	{
		id: "01",
		name: "Tuna salad",
		image: require("../assets/images/tuna.png"),
		rating: "4.2",
		ingredients: ["Canned Tuna", "Lemon Juice", "Onion", "Avocado"],
		time: "30 mins",
		difficulty: "Medium",
		calories: "450 cal",
		color: "lightgreen",
		description:
			"A light and satisfying salad featuring tender canned tuna combined with the tang of lemon juice, crisp red onion, and creamy avocado.",
		steps: [
			"Drain the canned tuna and flake it into a large bowl",
			"Finely chop the red onion and dice the avocado.",
			"Add the red onion and avocado to the tuna.",
			"Sueeze fresh lemon juice over the ingredients and mix gently.",
			"Chill the salad briefly, then serve fresh and enjoy!",
		],
	},
	{
		id: "02",
		name: "Chicken Lasagna",
		image: require("../assets/images/lasagna.png"),
		rating: "3.6",
		ingredients: [
			"Lasagna Noodles",
			"Chicken",
			"Cheese",
			"Tomato Sauce",
		],
		time: "40 mins",
		difficulty: "Medium",
		calories: "380 cal",
		color: "aquamarine",
		description:
			"A comforting twist on a classic, featuring layers of lasagna noodles, savory ground chicken, creamy ricotta cheese, and zesty tomato sauce.",
		steps: [
			"Cook the lasagna noodles according to package instructions",
			"Brown the ground chicken in a skillet and season with spices.",
			"Layer the lasagna noodles, ground chicken, ricotta cheese, and tomato sauce in a baking dish.",
			"Repeat the layers and bake in the oven until bubbly and golden on top.",
			"Allow to cool slightly before slicing and serving.",
		],
	},
	{
		id: "03",
		name: "Hot Dog",
		image: require("../assets/images/hotdog.png"),
		rating: "4.1",
		ingredients: ["Hot Dog Buns", "Frankfurters", "Ketchup", "Mustard"],
		time: "40 mins",
		difficulty: "Medium",
		calories: "420 cal",
		color: "cadetblue",
		description:
			"Indulge in a timeless American classic: succulent frankfurters nestled in soft hot dog buns, topped with a harmonious drizzle of ketchup and mustard for the quintessential taste.",
		steps: [
			"Cook the frankfurters on a grill or in a skillet until they are nicely browned and heated through.",
			"Place each cooked frankfurter into a fresh hot dog bun.",
			"Drizzle ketchup and mustard evenly over the frankfurters.",
			"Serve with your choice of classic sides like potato chips or coleslaw and enjoy the perfect bite!",
		],
	},
	{
		id: "04",
		name: "Manchurian",
		image: require("../assets/images/manchurian.png"),
		rating: "3.8",
		ingredients: ["Cauliflower", "Soy Sauce", "Ginger", "Garlic"],
		time: "35 mins",
		difficulty: "Easy",
		calories: "460 cal",
		color: "darkkhaki",
		description:
			"Enjoy the fusion of flavors with this beloved Indo-Chinese creation: crunchy cauliflower florets enrobed in a savory sauce crafted from soy sauce, ginger, and garlic for a delightful taste adventure.",
		steps: [
			"Chop the cauliflower into bite-sized florets and briefly blanch in boiling water.",
			"Combine soy sauce, finely minced ginger, and garlic to create the savory sauce.",
			"Fry the blanched cauliflower in oil until golden and crisp.",
			"Coat the crispy cauliflower thoroughly in the prepared sauce.",
			"Sprinkle with sliced green onions for garnish and serve immediately, piping hot.",
		],
	},
	{
		id: "05",
		name: "Chicken",
		image: require("../assets/images/chicken.png"),
		rating: "3.2",
		ingredients: ["Chicken Breasts", "Salt", "Black Pepper", "Olive Oil"],
		time: "40 mins",
		difficulty: "Medium",
		calories: "400 cal",
		color: "#darksalmon",
		description:
			"Savor the simplicity of this delectable chicken dish, where tender breasts are seasoned with just salt and black pepper, then seared in olive oil and roasted to juicy perfection",
		steps: [
			"Preheat the oven to 375°F (190°C).",
			"Generously season the chicken breasts with salt and freshly ground black pepper",
			"In a skillet, heat olive oil over medium-high heat",
			"Place the chicken in the skillet and sear on both sides until they achieve a golden-brown crust.",
			"Transfer the seared chicken to a baking dish and place in the oven",
			"Roast the chicken for about 20-25 minutes, or until the internal temperature reaches 165°F (74°C).",
			"Remove from the oven, let rest for a few minutes, and serve warm, drizzled with any juices from the pan.",
		],
	},
	{
		id: "06",
		name: "Cupcakes",
		image: require("../assets/images/cupcakes.png"),
		rating: "4.9",
		ingredients: ["Flour", "Sugar", "Eggs", "Butter"],
		time: "80 mins",
		difficulty: "Medium",
		calories: "230 cal",
		color: "deepskyblue",
		description:
			"Delightful cupcakes made with a perfect blend of flour, sugar, eggs, and butter, perfect for any occasion.",
		steps: [
			"Preheat the oven to the specified temperature.",
			"Prepare the cupcake batter by mixing the ingredients together.",
			"Line a muffin tin with cupcake liners.",
			"Fill each liner with batter and bake in the oven.",
			"Let the cupcakes cool, then frost and decorate as desired.",
			"Indulge in these sweet treats and savor the flavor!",
		],
	},
	{
		id: "07",
		name: "Curry",
		image: require("../assets/images/curry.png"),
		rating: "4.4",
		ingredients: ["Meat", "Curry Powder", "Coconut Milk", "Spices"],
		time: "55 mins",
		difficulty: "Hard",
		calories: "550 cal",
		color: "indianred",

		description:
			"Delve into the depths of flavor with this luxurious curry, where succulent meat pieces simmer in a rich sauce made from exotic curry spices and creamy coconut milk, creating an irresistibly aromatic experience",
		steps: [
			"Marinate the meat in a mixture of curry spices and allow it to rest for at least 30 minutes to enhance the flavor.",
			"Heat a generous amount of oil in a deep pot over medium-high heat and brown the marinated meat until it develops a rich color.",
			"Sprinkle curry powder over the meat and stir well to ensure each piece is evenly coated.",
			"Gradually pour in the coconut milk, stirring continuously to combine the flavors",
			"Reduce the heat, cover the pot, and let the curry gently simmer for about 1-2 hours, or until the meat is fork-tender.",
			"Adjust seasoning with salt and additional spices if needed. Allow the curry to rest for a few minutes before serving.",
			"Serve hot alongside fluffy rice or warm bread, garnishing with fresh herbs if desired.",
		],
	},
	{
		id: "08",
		name: "Ramen",
		image: require("../assets/images/ramen.png"),
		rating: "4.2",
		ingredients: ["Ramen Noodles", "Soy Sauce", "Eggs", "Vegetables"],
		time: "20 mins",
		difficulty: "Easy",
		calories: "360 cal",
		color: "cyan",
		description:
			"Experience the ultimate comfort with this heartwarming ramen bowl, packed with springy noodles, a rich soy-infused broth, crisp vegetables, and silky soft-boiled eggs for a satisfying meal any time.",
		steps: [
			"Prepare the ramen noodles by boiling them according to the instructions on the package; drain and set aside",
			"In a separate large pot, heat water and stir in soy sauce to create the flavorful broth",
			"Add your choice of chopped vegetables to the broth and simmer until they are just tender",
			"Meanwhile, boil eggs to your preferred level of doneness—soft, medium, or hard. Once done, cool them in ice water, peel, and cut into halves",
			"To assemble, distribute the cooked noodles evenly among bowls.",
			"Top the noodles with the simmered vegetables and arranged egg halves",
			"Pour the hot soy sauce broth over the noodles and toppings.",
			"Serve your homemade ramen hot, garnished with a sprinkle of green onions or a dash of chili flakes if desired. Enjoy the comfort in every slurp!",
		],
	},
];
